// <auto-generated />
namespace DKITMusicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class initial4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial4));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281301076_initial4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
